-- Seed curriculum modules (Levels 1–4). Safe to re-run.
INSERT INTO curriculum_modules (code, name, academic_level, semester_label, credits, compulsory_optional, chief_tutor, program_kind, mit_track) VALUES
('DELT 11232', 'English for Professionals', 1, '1', 2, 'C', NULL, 'ALL', NULL),
('GNCT 13212', 'Personal Progress Development I', 1, '1', 2, 'C', NULL, 'ALL', NULL),
('INTE 11213', 'Fundamentals of Computing', 1, '1', 3, 'C', NULL, 'ALL', NULL),
('INTE 11223', 'Programming Concepts', 1, '1', 3, 'C', NULL, 'ALL', NULL),
('MGTE 11233', 'Business Statistics and Economics', 1, '1', 3, 'C', NULL, 'ALL', NULL),
('MGTE 11243', 'Principles of Management & Organizational Behaviour', 1, '1', 3, 'C', NULL, 'ALL', NULL),
('PMAT 11212', 'Discrete Mathematics for Computing I', 1, '1', 2, 'C', NULL, 'ALL', NULL),
('MGTE 12253', 'Accounting Concepts and Costing', 1, '2', 3, 'C', NULL, 'ALL', NULL),
('INTE 12243', 'Computer Networks', 1, '2', 3, 'C', NULL, 'ALL', NULL),
('INTE 12213', 'Object Oriented Programming', 1, '2', 3, 'C', NULL, 'ALL', NULL),
('INTE 12223', 'Database Design and Development', 1, '2', 3, 'C', NULL, 'ALL', NULL),
('MGTE 12263', 'Optimization Methods in Management Science', 1, '2', 3, 'C', NULL, 'ALL', NULL),
('MGTE 12273', 'Industry and Technology', 1, '2', 3, 'C', NULL, 'ALL', NULL),
('PMAT 12212', 'Discrete Mathematics for Computing II', 1, '2', 2, 'C', NULL, 'ALL', NULL),
('INTE 21213', 'Information Systems Modelling', 2, '1', 3, 'C', NULL, 'IT', NULL),
('INTE 21313', 'Business Information Systems', 2, '1', 3, 'C', NULL, 'IT', NULL),
('INTE 21323', 'Web Applications Development', 2, '1', 3, 'C', NULL, 'IT', NULL),
('INTE 21333', 'Event Driven Programming', 2, '1', 3, 'C', NULL, 'IT', NULL),
('MGTE 21243', 'Marketing Management', 2, '1', 3, 'C', NULL, 'MIT', NULL),
('MGTE 21233', 'Operations Management', 2, '1', 3, 'C', NULL, 'MIT', NULL),
('INTE 21234', 'Software Engineering Concepts', 2, '1', 3, 'C', NULL, 'MIT', NULL),
('INTE 21243', 'Computer Architecture and Operating Systems', 2, '1', 3, 'C', NULL, 'IT', NULL),
('INTE 22293', 'Software Architecture and Process Models', 2, '2', 3, 'C', NULL, 'IT', NULL),
('INTE 22343', 'Data Structures and Algorithms', 2, '2', 3, 'C', NULL, 'ALL', NULL),
('INTE 22253', 'Distributed Systems and Cloud Computing', 2, '2', 3, 'C', NULL, 'IT', NULL),
('INTE 22263', 'Embedded Systems Development', 2, '2', 3, 'C', NULL, 'IT', NULL),
('INTE 22303', 'Artificial Intelligence', 2, '2', 3, 'C', NULL, 'ALL', NULL),
('INTE 22213', 'Software Design Patterns and Frameworks', 2, '2', 3, 'C', NULL, 'IT', NULL),
('INTE 22283', 'Mobile Applications Development', 2, '2', 3, 'C', NULL, 'ALL', NULL),
('GNCT 23212', 'Personal Progress Development II', 2, '2', 2, 'C', NULL, 'ALL', NULL),
('MGTE 22273', 'Human Resource Management & Leadership Communication', 2, '2', 3, 'C', NULL, 'MIT', NULL),
('MGTE 22263', 'Logistics and Supply Chain Management', 2, '2', 3, 'C', NULL, 'MIT', NULL),
('INTE 31233', 'Human Computer Interaction', 3, '1', 3, 'C', NULL, 'IT', NULL),
('INTE 31393', 'Information Security', 3, '1', 3, 'C', NULL, 'ALL', NULL),
('INTE 31356', 'Software Development Project', 3, '1', 6, 'C', NULL, 'ALL', NULL),
('MGTE 31373', 'Project Management', 3, '1', 3, 'C', NULL, 'ALL', NULL),
('INTE 31243', 'Software Quality Engineering', 3, '1', 3, 'O', NULL, 'IT', NULL),
('INTE 31283', 'Big Data and Data Warehousing', 3, '1', 3, 'O', NULL, 'IT', NULL),
('INTE 31373', 'Machine Learning', 3, '1', 3, 'O', NULL, 'IT', NULL),
('INTE 31403', 'System Administration and Maintenance', 3, '1', 3, 'O', NULL, 'IT', NULL),
('MGTE 31383', 'Research Methods', 3, '1', 3, 'O', NULL, 'ALL', NULL),
('PMAT 31212', 'Mathematics for Computing - 3', 3, '1', 2, 'O', NULL, 'IT', NULL),
('GNCT 32216', 'Internship', 3, '2', 6, 'C', NULL, 'ALL', NULL),
('MGTE 31393', 'Managerial Finance', 3, '1', 3, 'C', NULL, 'MIT', NULL),
('MGTE 31293', 'Computer Integrated Manufacturing', 3, '1', 3, 'C', NULL, 'MIT', NULL),
('MGTE 31403', 'Management of Technology', 3, '1', 3, 'C', NULL, 'MIT', NULL),
('MGTE 31413', 'Warehouse Management and Industrial Shipping', 3, '1', 3, 'C', NULL, 'MIT', NULL),
('MGTE 31423', 'Advanced Optimization Methods in Management Science', 3, '1', 3, 'C', NULL, 'MIT', NULL),
('MGTE 31433', 'Computer based tools for Management Applications', 3, '1', 3, 'O', NULL, 'MIT', NULL),
('MGTE 31303', 'Procurement and Supply Management', 3, '1', 3, 'O', NULL, 'MIT', NULL),
('MGTE 31443', 'Strategic Marketing and International Trade', 3, '1', 3, 'O', NULL, 'MIT', NULL),
('INTE 31423', 'Data Analytics and Visualization', 3, '1', 3, 'O', NULL, 'MIT', NULL),
('INTE 31413', 'Information Technology Infrastructure', 3, '1', 3, 'O', NULL, 'MIT', NULL),
('INTE 43216', 'Research Project', 4, '1 & 2', 6, 'C', NULL, 'ALL', NULL),
('MGTE 41313', 'Statistical Data Modeling', 4, '1', 3, 'C', NULL, 'ALL', NULL),
('MGTE 41323', 'Professional Practices', 4, '1', 3, 'C', NULL, 'ALL', NULL),
('INTE 41393', 'System Integration Technologies', 4, '1', 3, 'C', NULL, 'IT', NULL),
('INTE 41373', 'Image Processing', 4, '1', 3, 'O', NULL, 'IT', NULL),
('INTE 41323', 'Neural Networks and Deep Learning', 4, '1', 3, 'O', NULL, 'IT', NULL),
('INTE 41383', 'Industrial Automation', 4, '1', 3, 'O', NULL, 'IT', NULL),
('INTE 41403', 'Advanced Databases', 4, '1', 3, 'O', NULL, 'IT', NULL),
('INTE 41413', 'Internet of Things', 4, '1', 3, 'O', NULL, 'IT', NULL),
('MGTE 42303', 'Business and Information Technology Law', 4, '2', 3, 'C', NULL, 'ALL', NULL),
('MGTE 41333', 'Business Process Engineering', 4, '1', 3, 'C', NULL, 'MIT', NULL),
('MGTE 41233', 'Corporate Finance', 4, '1', 3, 'O', NULL, 'MIT', NULL),
('INTE 41283', 'Information Systems Management and Strategy', 4, '1', 3, 'O', NULL, 'MIT', NULL),
('MGTE 41303', 'Enterprise Systems', 4, '1', 3, 'O', NULL, 'MIT', NULL),
('MGTE 41343', 'Logistics System Analysis and Geomatics', 4, '1', 3, 'O', NULL, 'MIT', NULL),
('MGTE 41353', 'Sustainability and Economics in Logistics and Supply Chain', 4, '1', 3, 'O', NULL, 'MIT', NULL),
('MGTE 41363', 'Digital Innovations Management', 4, '1', 3, 'O', NULL, 'MIT', NULL),
('MGTE 41373', 'Strategic Management', 4, '1', 3, 'O', NULL, 'MIT', NULL),
('MGTE 41383', 'Advanced operations Management', 4, '1', 3, 'O', NULL, 'MIT', NULL),
('MGTE 44273', 'Innovation & Entrepreneurship', 4, '1 OR 2', 3, 'O', NULL, 'MIT', NULL),
('INTE 43003', 'Information Audit and Assurance', 4, '1 OR 2', 3, 'O', NULL, 'MIT', NULL),
('MGTE 42323', 'Strategic Quality Management and Lean Six Sigma', 4, '2', 3, 'O', NULL, 'MIT', NULL),
('MGTE 42213', 'Industrial and Systems Engineering', 4, '2', 3, 'C', NULL, 'MIT', NULL),
('MGTE 42313', 'Advanced Supply Chain and Logistics Applications', 4, '2', 3, 'O', NULL, 'MIT', NULL),
('MGTE 42243', 'Advanced Planning and Scheduling', 4, '2', 3, 'O', NULL, 'MIT', NULL),
('MGTE 42233', 'Investment Management', 4, '2', 3, 'O', NULL, 'MIT', NULL),
('INTE 42353', 'Semantic Web and Ontological Engineering', 4, '2', 3, 'O', NULL, 'IT', NULL),
('INTE 42333', 'Complex Systems and Agent-Based Modelling', 4, '2', 3, 'O', NULL, 'IT', NULL),
('INTE 42343', 'Natural Language Processing', 4, '2', 3, 'O', NULL, 'IT', NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    academic_level = EXCLUDED.academic_level,
    semester_label = EXCLUDED.semester_label,
    credits = EXCLUDED.credits,
    compulsory_optional = EXCLUDED.compulsory_optional,
    chief_tutor = EXCLUDED.chief_tutor,
    program_kind = EXCLUDED.program_kind,
    mit_track = EXCLUDED.mit_track;;
